---
title: "realdata"
author: "zhuofan wang"
date: "2021/12/16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rpkm <- read.table("C://ISBD/bicluster code/all.txt",nrows = 10,skip = 2)
mid <- read.table("C://ISBD/bicluster code/rpkm.txt")
read_count <- read.table("C://ISBD/bicluster code/gene.txt",skip = 2)
name_gene <- read_count$V2[-1]
sum_gene <- rowSums(mid[,-(1:2)])
non_zero <- which(sum_gene!=0)
length(table(name_gene))
id <- as.character(read_count[1,-(1:2)])
id_split <- strsplit(id,"-")
id_donor <- unlist(lapply(id_split,function(x){return(x[2])}))
td <- table(id_donor)
id_tissue <- unlist(lapply(id_split,function(x){return(x[3])}))
tt <- table(id_tissue)
length(table(id_tissue))
sum_gene
```

```{r}
condition <- factor(id_tissue)
count_mat <- as.matrix(read_count[2:10,-(1:2)])
count_mat <- apply(count_mat,c(1,2), as.numeric)
dds <-DESeq2::DESeqDataSetFromMatrix(count_mat,data.frame(condition), ~ condition)

```

```{r}
tt
ind <- which(id_tissue=="0011")
inf <- id[ind]
inf
```

```{r}
tt

```

```{r}
td

```

```{r}
rown <- read_count$V1[-1]
coln <- read_count[1,][-(1:2)]
coln <- as.character(coln)

```

```{r}
read_count <- read_count[-1,-(1:2)]

```

```{r}
for(j in 1:ncol(read_count)){
  read_count[,j]=as.numeric(read_count[,j])
}

```

```{r}
test <- as.matrix(read_count)
test <- as.numeric(test)
test <- matrix(test,nrow = 56318)
```

```{r}
adj <- function(x){
  if(length(x)==0) 
    x <- NA 
  if(length(x) >0)  
    x <- min(x)
  return(x)
}
ind_split <- split(1:8540,list(as.factor(donor_adj),as.factor(tissue_adj)))
ind_adj <- lapply(ind_split, adj)
ind_vec <- as.numeric(unlist(ind_adj))
ind_mat <- matrix(ind_vec,nrow = 544)
```

```{r}
condition <- as.factor(id_tissue)
dds <- DESeqDataSetFromMatrix(test, DataFrame(condition), ~ condition)
dds <- estimateSizeFactors(dds)
sf <- sizeFactors(dds)
count_scale <- t(t(read_count)/sf)
count_scale <- matrix(NA,nrow = 56318,ncol = 8555)
for(j in 1:ncol(read_count)){
  count_scale[,j]=(read_count[,j]/sf[j])
}
del_tis <- name_tis[which(tt<15)]
keep_col <- which(is.na(match(id_tissue,del_tis)))
keep_row <- which(rowSums(count_scale)/8555>=500)

count_adj <- count_scale[keep_row,keep_col]
```

```{r}
tissue_adj <- id_tissue[keep_col]
donor_adj <- id_donor[keep_col]
```

```{r}
table(tissue_adj)
```

```{r}
tissue0126 <- which(tissue_adj=="0126")
tissue0226 <- which(tissue_adj=="0226")
tissue0326 <- which(tissue_adj=="0326")
tissue0426 <- which(tissue_adj=="0426")
tissue0526 <- which(tissue_adj=="0526")
tissue0626 <- which(tissue_adj=="0626")
tissue0726 <- which(tissue_adj=="0726")
tissue0826 <- which(tissue_adj=="0826")
tissue0926 <- which(tissue_adj=="0926")
```

```{r}
kg <- 12092
farray <- function(x){
  if(is.na(x)==1)
    return(rep(NA,kg))
  else
    return(count_adj[,x])
}
count_array <- apply(ind_mat, c(1,2), farray)
sum(is.na(count_array))
```

```{r}
head(count_adj)
```

--------Deal with brain data--------

```{r}

brain_data <- read.table("C://ISBD/bicluster code/brain_data.csv")
brain_data <- read.csv("C://ISBD/bicluster code/0220/brainscale1.csv")
targene <- brain_data$X
brain_mat <- as.matrix(brain_data[,-1])
id <- read.table("C://ISBD/bicluster code/id.csv")
id <- id$x
```

```{r}
library(data.table)
att <- fread("https://storage.googleapis.com/gtex_analysis_v6/annotations/GTEx_Data_V6_Annotations_SampleAttributesDS.txt")

```

```{r}
library(dplyr)
brain <- filter(att,SMTS=="Brain")
```

```{r}
head(brain)
```

```{r}
id <- read.table("id.csv")
id <- id$x
brain_id <-id[which(!is.na(match(id,brain$SAMPID)))]
br_split <- strsplit(brain_id,"-")
don_br <- unlist(lapply(br_split,function(x){return(x[2])}))
don_set <- names(table(don_br))
att_br <- brain[(match(brain_id,brain$SAMPID)),]
tis_br <- att_br$SMTSD
tis_set <- names(table(tis_br))
```

```{r}
brain_mat <- read_count[,which(!is.na(match(id,brain$SAMPID)))]
#kepprow <- order(apply(brain_mat, 1, mean),decreasing=TRUE)[1:10]
tar_gene1 <- c("GFAP","SLC1A2","CNP","MBP","MOBP","MOG","A2M","CLDN5")
#tar_gene2 <- c("A2M","ACE","APBB2","APOE","APP","BLMH","KLK6","NOS3","PLAU","SEN1","PSEN2","CCK","ADRBK2","MDGA1")
keeprow <- match(tar_gene1,name_gene)
keeprow <- na.omit(keeprow)
brain_mat <- brain_mat[keeprow,]
#gene_br <- mid$V2[kepprow]
```

```{r}
adj <- function(x){
  if(length(x)==0) 
    x <- NA 
  if(length(x) >0)  
    x <- min(x)
  return(x)
}
ind_split <- split(1:1259,list(as.factor(don_br),as.factor(tis_br)))
ind_adj <- lapply(ind_split, adj)
ind_vec <- as.numeric(unlist(ind_adj))
ind_mat <- matrix(ind_vec,nrow = 193)
```

```{r}
kg <- 8
farray <- function(x){
  if(is.na(x)==1)
    return(rep(NA,kg))
  else
    return(brain_mat[,x])
}
brain_array <- apply(ind_mat, c(1,2), farray)
brain_array <- aperm(brain_array,c(2,3,1))
```

```{r}
library(data.table)
sub_att <- fread("https://storage.googleapis.com/gtex_analysis_v6/annotations/GTEx_Data_V6_Annotations_SubjectPhenotypesDS.txt")
subsplit  <- strsplit(sub_att$SUBJID,"-")
subid <- unlist(lapply(subsplit,function(x){return(x[2])}))
subbr_att <- sub_att[match(don_set,subid),]
subbr_att$AGE[subbr_att$AGE=="20-29"] <- 1
subbr_att$AGE[subbr_att$AGE=="30-39"] <- 2
subbr_att$AGE[subbr_att$AGE=="40-49"] <- 3
subbr_att$AGE[subbr_att$AGE=="50-59"] <- 4
subbr_att$AGE[subbr_att$AGE=="60-69"] <- 5
subbr_att$AGE[subbr_att$AGE=="70-79"] <- 6

subbr_att <- subbr_att[,-1]
```

```{r}
library(caret)
for(i in 1:13){
  for(j in 1:8){
    teid <- which(is.na(brain_array[,i,j]))
    if(length(teid)>0){
      trainx <- subbr_att[-teid,-3]
      trainy <- brain_array[-teid,i,j]
      testx <- subbr_att[teid,-3]
      testy <- knnregTrain(trainx, testx, trainy, k = 10, use.all = TRUE)
      brain_array[teid,i,j] <- testy
    }
  }
}
sum(is.na(brain_array))  
#brain_array <- brain_array/mean(brain_array)
```

```{r}
brain_array <- log(brain_array)
brain_array <- brain_array-mean(brain_array)
```

```{r}
for(i in 1:13)
  for(j in 1:8){
    hist(brain_array[,i,j])
  }
```

```{r}
y <- brain_array

{
  set.seed(10)
  c1track <- list()
  c2track <- list()
  c3track <- list()
  ztrack <- list()
  #//initialization
  al=1;bl=3;av=1;bv=1;am=1;bm=1;sigmal=1;mub=-1;sigmab=0.1;arho=1;brho=1;psi_1=1/3;psi0=1/3;psi1=1/3;as=1;bs=1;sigmamu=1;
 
  #//dimension
  d=dim(y);
  
 #//class number
  r=1;
  #//observation and latent
  #cube z=randi<cube>(d[0],d[1],d[2],distr_param(-1,1));
  #//class
#c3o[c3o == 1] = 2 * (runif(sum(c3o == 1)) < 0.5) - 1
  c1 = matrix(as.numeric(runif(d[1] * r) < 0.5), d[1], r)
  c2 =matrix(as.numeric(runif(d[2] * r) < 0.5), d[2], r)
 
  c3 = matrix(as.numeric(runif(d[3] * r) < 0.5), d[3], r)
 #c3[c3 == 1] = 2 * (runif(sum(c3 == 1)) < 0.5) - 1
  #c1 <- c1o
  #c2 <- c2o
  #c3 <- c3o
  #z <- array(0,dim = d)
  #mat lambda1(d[2],r,fill::randn);
  #mat lambda2(d[2],r,fill::randn);
  #lambda1 = matrix(lambda1[,1],ncol = 1)
  #lambda2 = matrix(lambda2[,1],ncol = 1)
  #lambda1 <- matrix(rgamma(d[3]*r, al, 1/bl), d[3],r)
  #lambda2 <- matrix(rgamma(d[3]*r, al, 1/bl), d[3],r)
  lambda1 <- matrix(rgamma(d[3]*r,1,1/3),nrow = d[3],byrow = TRUE)
  lambda2 <- lambda1
  #//paramters
  mu <- apply(y, c(2,3), mean)
  sigma2 <- matrix(1,nrow = d[2],ncol = d[3])
  v1 <- 7*sigma2
  v2 <- v1
  #b1 <- matrix(rnorm(d[2]*d[3]),nrow = d[2],ncol = d[3])
  b1 <- matrix(-2.3,nrow = d[2],ncol = d[3])
  
  b2 <-b1
  #mat mu(d[1],d[2],fill::zeros);
  #mat v1(d[1],d[2],fill::randu);
  #mat v2(d[1],d[2],fill::randu);
  #mat sigma2(d[1],d[2],fill::ones);
  #mat b1(d[1],d[2],fill::randn);
  #mat b2(d[1],d[2],fill::randn);
  m=0.5;rho=0.1;
  
  #vec gamma(3,fill::randu);
  gamma <- c(rho/2,1-rho,rho/2)
  #z <- z0
  z <- array(0,dim = d)
}
  #//MCMC update
set.seed(2)
  for(it in 10001:50000){
    #ztrack[[it]] <- z
    li4 <- update_zv(c1,c2,c3,lambda1,lambda2,d,z,b1,b2,v1,v2,av,bv,y,mu,sigma2);
    z <- li4[[1]]
    v1 <- li4[[2]]
    v2 <- li4[[3]]
    li1 <- update_c1(c1,c2,c3,lambda1,lambda2,d,z,b1,b2,gamma, m,rho,al,bl)
    c1 <- li1[[1]]
    c2 <- li1[[2]]
    c3 <- li1[[3]]
    
    lambda1 <- li1[[4]]
    
    lambda2 <- li1[[5]]
    r <- ncol(c1)
    
    c2 <- update_c2(c1,c2,c3,lambda1,lambda2,d,z,b1,b2,rho);
    li2 <-  update_c3(c1,c2,c3,lambda1,lambda2,d,z,b1,b2,gamma,sigmal,al,bl)
    c3 <-li2[[1]]
    lambda1 <- li2[[2]]
    lambda2 <- li2[[3]]
    
    #m <- rgamma(1,am+r,bm+har(d[1]))
    #m = randg( distr_param(am+r,bm+har(d[0])));
    #//update $\rho$
    #rho <-  rbeta(1,arho+sum(c2),brho+d[2]*r-sum(c2))
    #//update $\gamma$
    #probs <- c(psi_1+sum(c3==-1),psi0+sum(c3==0),psi1+sum(c3==1))
    #gamma <- rdirichlet(1,probs)
    #//update $b_1,b_2$
    #li5 <- update_b(d,mub,sigmab,b1,b2,c1,c2,c3,lambda1,lambda2,z);
    li5 <- update_bunit(d,mub,sigmab,b1,b2,c1,c2,c3,lambda1,lambda2,z)
    b1 <- li5[[1]]
    b2 <- li5[[2]]
    
    #up6 = update_norm(z,y,sigmamu,mu,v1,v2);
    #sigma2 <- up6[1:d[2],]
    #mu <- up6[(d[2]+1):(2*d[2]),]
    #result_multi[[it]] <- rbind(c1,c2,c3)
    
    sigma2 <- update_norm1(z,y,mu,v1,v2)
    mu <- update_norm2(z,y,sigmamu,sigma2)
    c1track[[it]] <- c1
    c2track[[it]] <- c2
    c3track[[it]] <- c3
  }
  return matrix_gibbs;
}

```

```{r}


{
  set.seed(1)
  c1track <- list()
  c2track <- list()
  c3track <- list()
  #ztrack <- list()
  #b1track <- list()
  #b2track <- list()
  #//initialization
  al=1;bl=3;av=1;bv=10;am=1;bm=1;sigmal=1;mub=-2;sigmab=1;arho=1;brho=1;psi_1=1/3;psi0=1/3;psi1=1/3;as=1;bs=1;sigmamu=1;
 
  #//dimension
  d=dim(y);
  
 #//class number
  r=1;
  #//observation and latent
  #cube z=randi<cube>(d[0],d[1],d[2],distr_param(-1,1));
  #//class
#c3o[c3o == 1] = 2 * (runif(sum(c3o == 1)) < 0.5) - 1
  c1 = matrix(as.numeric(runif(d[1] * r) < 0.5), d[1], r)
  c2 =matrix(as.numeric(runif(d[2] * r) < 0.5), d[2], r)
 
  c3 = matrix(as.numeric(runif(d[3] * r) < 0.5), d[3], r)
 #c3[c3 == 1] = 2 * (runif(sum(c3 == 1)) < 0.5) - 1
  #c1 <- c1o
  #c2 <- c2o
  #c3 <- c3o
  #z <- array(0,dim = d)
  #mat lambda1(d[2],r,fill::randn);
  #mat lambda2(d[2],r,fill::randn);
  #lambda1 = matrix(lambda1[,1],ncol = 1)
  #lambda2 = matrix(lambda2[,1],ncol = 1)
  #lambda1 <- matrix(rgamma(d[3]*r, al, 1/bl), d[3],r)
  #lambda2 <- matrix(rgamma(d[3]*r, al, 1/bl), d[3],r)
  #lambda1 <- matrix(rep(l1[1],d[3]),nrow = d[3],byrow = TRUE)
  lambda1 <- matrix(rgamma(d[3]*r,1,1/3),nrow = d[3],byrow = TRUE)
  lambda2 <- lambda1
  #//paramters
  mu <- matrix(0,nrow = d[2],ncol = d[3])
  sigma2 <- matrix(1,nrow = d[2],ncol = d[3])
  v1 <- 5*sigma2
  v2 <- v1
  #b1 <- matrix(rnorm(d[2]*d[3]),nrow = d[2],ncol = d[3])
  #b1 <- b1m
  b1 <- matrix(-2.3,nrow = d[2],ncol = d[3])
  b2 <-b1
  #mat mu(d[1],d[2],fill::zeros);
  #mat v1(d[1],d[2],fill::randu);
  #mat v2(d[1],d[2],fill::randu);
  #mat sigma2(d[1],d[2],fill::ones);
  #mat b1(d[1],d[2],fill::randn);
  #mat b2(d[1],d[2],fill::randn);
  m=1;rho=0.3;
  
  #vec gamma(3,fill::randu);
  gamma <- c(rho/2,1-rho,rho/2)
  #z <- z0
  z <- array(0,dim = d)
}
  #//MCMC update
set.seed(2)
  for(it in 1:5000){
    #ztrack[[it]] <- z
    
    
    li4 <- update_zv(c1,c2,c3,lambda1,lambda2,d,z,b1,b2,v1,v2,av,bv,y,mu,sigma2);
    z <- li4[[1]]
    v1 <- li4[[2]]
    v2 <- li4[[3]]
    li1 <- update_c1(c1,c2,c3,lambda1,lambda2,d,z,b1,b2,gamma, m,rho,al,bl)
    c1 <- li1[[1]]
    c2 <- li1[[2]]
    c3 <- li1[[3]]
    lambda1 <- li1[[4]]
    lambda2 <- li1[[5]]
    r <- ncol(c1)
    
    c2 <- update_c2(c1,c2,c3,lambda1,lambda2,d,z,b1,b2,rho);
    li2 <-  update_c3(c1,c2,c3,lambda1,lambda2,d,z,b1,b2,gamma,sigmal,al,bl)
    c3<-li2[[1]]
    lambda11 <- li2[[2]]
    lambda21 <- li2[[3]]
    
    #m <- rgamma(1,am+r,bm+har(d[1]))
    #m = randg( distr_param(am+r,bm+har(d[0])));
    #//update $\rho$
    #rho <-  rbeta(1,arho+sum(c2),brho+d[2]*r-sum(c2))
    #//update $\gamma$
    #probs <- c(psi_1+sum(c3==-1),psi0+sum(c3==0),psi1+sum(c3==1))
    #gamma <- rdirichlet(1,probs)
    #//update $b_1,b_2$
    #li5 <- update_b(d,mub,sigmab,b1,b2,c1,c2,c3,lambda1,lambda2,z);
    
    li5 <- update_bunit(d,mub,sigmab,b1,b2,c1,c2,c3,lambda1,lambda2,z)
    b1 <- li5[[1]]
    b2 <- li5[[2]]
    #up6 = update_norm(z,y,sigmamu,mu,v1,v2);
    sigma2 <- update_norm1(z,y,mu,v1,v2)
    mu <- update_norm2(z,y,sigmamu,sigma2)
    #result_multi[[it]] <- rbind(c1,c2,c3)
    c1track[[it]] <- c1
    c2track[[it]] <- c2
    c3track[[it]] <- c3
    #b1track[[it]] <- b1
    #b2track[[it]] <- b2
  }
  return matrix_gibbs;
}

```

```{r}

kclass <- vector()
for(i in 1:length(c1track)){
  kclass[i] <- ncol(c1track[[i]])
}
plot(kclass)
table(kclass)
```

```{r}

kclass <- vector()
for(i in 5001:10000){
  kclass[i] <- ncol(c1track[[i]])
}
plot(kclass)
table(kclass)
```

```{r}
tis_li <- strsplit(tis_set,"-")
tis_set2 <- unlist(lapply(tis_li,function(x){return(x[2])}))
```

```{r}
c1 <- c1track[[5000]]
c2 <- c2track[[5000]]
c3 <- c3track[[5000]]
```

```{r}
rownames(c1) <- don_set
rownames(c2) <- tis_set
rownames(c3) <- tar_gene2[-10]
colnames(c1) <- c("class1","class2","class3","class4","class5","class6")#,"class7","class8","class9","class10","class11","class12")
colnames(c2) <- c("class1","class2","class3","class4","class5","class6")#,"class7","class8","class9","class10","class11","class12")
colnames(c3) <- c("class1","class2","class3","class4","class5","class6")#,"class7","class8","class9","class10","class11","class12")
```

```{r}
library(dplyr)
br_att <- cbind(don_set,subbr_att)
a <- arrange(br_att,GENDER,AGE,DTHHRDY)
don_arr <- a$don_set

```

```{r}
ind6 <- which(unlist(lapply(c1track, function(x){ncol(x)}))==6)

c16 <- 
  
c26 <- 
  
c36 <- 
```

```{r}
kl <- 7
#kclass <- vector()
c3left <- c3track[which(kclass==kl)]
c3pp <- matrix(0,nrow = d[3]*kl,ncol = sum(na.omit(kclass==kl)))
for(t in 1:length(c3left)){
 # kclass[i] <- ncol(c1track[[i]])
  c3pp[,t] <- as.vector(c3left[[t]])
}
c3ppp <- apply(c3pp, 1, function(x){as.numeric(names(table(x))[table(x) == max(table(x))])})
#plot(kclass)
c3ppp <- matrix(c3ppp,nrow = d[3],ncol = kl)
```

```{r}
kl <- 8
#kclass <- vector()
c1left <- c1track[which(kclass==kl)]
c1pp <- matrix(0,nrow = d[1]*kl,ncol = sum(na.omit(kclass==kl)))
for(t in 1:length(c1left)){
 # kclass[i] <- ncol(c1track[[i]])
  c1pp[,t] <- as.vector(c1left[[t]])
}
c1ppp <- unlist(apply(c1pp, 1, function(x){min(as.numeric(names(table(x))[table(x) == max(table(x))]))}))
#plot(kclass)
c1ppp <- matrix(c1ppp,nrow = d[1],ncol = kl)
```

```{r}
kl <- 5
#kclass <- vector()
c2left <- c2track[1:1000]
c2pp <- matrix(0,nrow = d[2]*kl,ncol = sum(na.omit(kclass==kl)))
for(t in 1:length(c2left)){
 # kclass[i] <- ncol(c1track[[i]])
  c2pp[,t] <- as.vector(c2left[[t]])
}
c2ppp <- apply(c2pp, 1, function(x){as.numeric(names(table(x))[table(x) == max(table(x))])})
#plot(kclass)
c2ppp <- matrix(c2ppp,nrow = d[2],ncol = kl)
```

```{r}
c1_arr <- c1ppp[match(don_arr,don_set),]
c1_arr <- c1p[match(don_arr,don_set),]
```

```{r}
rownames(c1_arr) <- don_arr
rownames(c2ppp) <- tis_set
rownames(c3ppp) <- tar_gene1
```

```{r}
don_arr <- don_set
rownames(c1) <- don_arr
rownames(c2n) <- tis_set
name_genedel3 <- gcgene[-del]
name_genedel3 <- name_genedel3[-del2]
name_genedel3 <- name_genedel3[-del3]
rownames(c3) <- genefo
rownames(c3n) <- dep_gene
```

```{r}
library(reshape2)
#pc2o = melt(t(c1o), varnames = c("Factor", "secondorder"), value.name = "Indicator")
pc1p = melt(t(c1n), varnames = c("Factor", "secondorder"), value.name = "Indicator")
```

```{r}
library(ggplot2)
#ggplot2::ggplot(pc2o, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc1p, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none",axis.text.x = element_text(size = 5, angle = 45)) +
  scale_x_discrete(expand = c(0, 0),guide = guide_axis(n.dodge=10)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")

```

```{r}
library(reshape2)
#pc2o = melt(t(c1o), varnames = c("Factor", "secondorder"), value.name = "Indicator")
pc2p = melt(t(c2n), varnames = c("Factor", "secondorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc2o, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc2p, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  scale_x_discrete(expand = c(0, 0),guide = guide_axis(n.dodge=5)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
```

```{r}
#pc3o = melt(t(c3o), varnames = c("Factor", "thirdorder"), value.name = "Indicator")
pc3ppp = melt(t(c3n), varnames = c("Factor", "thirdorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc3o, aes(x = thirdorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradientn(colors = c("red", "black", "green"), breaks = c(-1, 0, 1)) + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc3ppp, aes(x = thirdorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradientn(colors = c("red", "black", "green"), breaks = c(-1, 0, 1)) + theme(legend.position = "none") +
  scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
```

```{r}
library(reshape2)
#pc2o = melt(t(c1o), varnames = c("Factor", "secondorder"), value.name = "Indicator")
pc1p = melt(t(c1p), varnames = c("Factor", "secondorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc2o, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc1p, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none",axis.text.x = element_text(size = 5, angle = 45)) +
  scale_x_discrete(expand = c(0, 0),guide = guide_axis(n.dodge=10)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")

```

```{r}
#pc2o = melt(t(c1o), varnames = c("Factor", "secondorder"), value.name = "Indicator")
pc1pp = melt(t(c1ppp), varnames = c("Factor", "secondorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc2o, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc1pp, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none",axis.text.x = element_text(size = 5, angle = 45)) +
  scale_x_discrete(expand = c(0, 0),guide = guide_axis(n.dodge=10)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")

```

```{r}
#pc2o = melt(t(c1o), varnames = c("Factor", "secondorder"), value.name = "Indicator")
pc1a = melt(t(c1_arr), varnames = c("Factor", "secondorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc2o, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc1a, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none",axis.text.x = element_text(size = 5, angle = 45)) +
  scale_x_discrete(expand = c(0, 0),guide = guide_axis(n.dodge=10)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")

```

```{r}
#pc2o = melt(t(c1o), varnames = c("Factor", "secondorder"), value.name = "Indicator")
pc2p = melt(t(c2), varnames = c("Factor", "secondorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc2o, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc2p, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  scale_x_discrete(expand = c(0, 0),guide = guide_axis(n.dodge=5)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")

```

```{r}
library(reshape2)
#pc2o = melt(t(c1o), varnames = c("Factor", "secondorder"), value.name = "Indicator")
pc2p = melt(t(c2ppp), varnames = c("Factor", "secondorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc2o, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc2p, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  scale_x_discrete(expand = c(0, 0),guide = guide_axis(n.dodge=5)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
```

```{r}
#pc3o = melt(t(c3o), varnames = c("Factor", "thirdorder"), value.name = "Indicator")
pc3p = melt(t(c3), varnames = c("Factor", "thirdorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc3o, aes(x = thirdorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradientn(colors = c("red", "black", "green"), breaks = c(-1, 0, 1)) + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc3p, aes(x = thirdorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradientn(colors = c("red", "black", "green"), breaks = c(-1, 0, 1)) + theme(legend.position = "none") +
  scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
```

```{r}
#pc3o = melt(t(c3o), varnames = c("Factor", "thirdorder"), value.name = "Indicator")
pc3ppp = melt(t(c3ppp), varnames = c("Factor", "thirdorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc3o, aes(x = thirdorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradientn(colors = c("red", "black", "green"), breaks = c(-1, 0, 1)) + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc3ppp, aes(x = thirdorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradientn(colors = c("red", "black", "green"), breaks = c(-1, 0, 1)) + theme(legend.position = "none") +
  scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
```

```{r}
del <- c(1,2,3,11)
c3_del <- c3[,-del]
#pc3o = melt(t(c3o), varnames = c("Factor", "thirdorder"), value.name = "Indicator")
pc3p = melt(t(c3_del), varnames = c("Factor", "thirdorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc3o, aes(x = thirdorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradientn(colors = c("red", "black", "green"), breaks = c(-1, 0, 1)) + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc3p, aes(x = thirdorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradientn(colors = c("red", "black", "green"), breaks = c(-1, 0, 1)) + theme(legend.position = "none") +
  scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
```

```{r}
c2_del <- c2[,-del]
#pc2o = melt(t(c1o), varnames = c("Factor", "secondorder"), value.name = "Indicator")
pc2p = melt(t(c2_del), varnames = c("Factor", "secondorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc2o, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc2p, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  scale_x_discrete(expand = c(0, 0),guide = guide_axis(n.dodge=5)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")

```

```{r}
c1_del <- c1[,-del]
#pc2o = melt(t(c1o), varnames = c("Factor", "secondorder"), value.name = "Indicator")
pc1p = melt(t(c1_del), varnames = c("Factor", "secondorder"), value.name = "Indicator")
```

```{r}
#ggplot2::ggplot(pc2o, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
 # scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none") +
  #scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")
ggplot2::ggplot(pc1p, aes(x = secondorder, y = Factor)) + geom_tile(aes(fill = Indicator), color = "black") +
  scale_fill_gradient(low = "black", high = "green") + theme(legend.position = "none",axis.text.x = element_text(size = 5, angle = 45)) +
  scale_x_discrete(expand = c(0, 0),guide = guide_axis(n.dodge=10)) + scale_y_discrete(expand = c(0, 0)) + labs(x = "", y = "")

```

```{r}
set.seed(1)
c <- matrix(0,nrow = 10,ncol = 3)
d <- matrix(0,nrow = 10,ncol = 3)

for(i in 1:3){
  c[,i] <- randarma1(5)
  d[,i] <- randarma2(5)
}

```

```{r}
ishgene <- read.table("gene.txt",sep="\t",quote = "")
genetable <- sort(table(ishgene$V1))
brain_gene <- names(table(ishgene$V1))
brain_gene <- brain_gene[-c(26,185,214)]
targene3 <- names(genetable)[as.vector(genetable)==3|as.vector(genetable)==4]
keeprow <- match(targene3,name_gene)
brain_mat <- brain_mat[keeprow,]
rownames(brain_mat) <- targene3

keeprow2 <- which((rowMeans(brain_mat)<1e4) &(rowMeans(brain_mat)>1e3))
brain_mat <- brain_mat[keeprow2,]
name_gene <- read.csv("namegene.csv")
name_gene <- name_gene$x
```

```{r}
gcgene <- read.table("C://ISBD/bicluster code/0228/gcgene.txt",sep="\t",quote = "")
gcgene <- gcgene$V1
gcd <- match(gcgene,name_gene)
gcd <- na.omit(gcd)
gcd <- which(!is.na(match(kr,gcd)))
```

```{r}
alz <- read.table("C://ISBD/bicluster code/0317/alzheimer.txt",sep="\t",quote = "")
alz <- alz$V1
alzd <- match(alz,name_gene)
alzd <- na.omit(alzd)
alzd <- which(!is.na(match(kr,alzd)))
```

```{r}
indg <- match(brain_gene,name_gene)
brain_scale <- matrix(nrow = length(brain_gene),ncol = 8555)
for(i in length(brain_gene)){
  brain_scale[i] <- read.csv("C://ISBD/bicluster code/0228/count_scale.csv",skip = indg[i]-1,nrows = 1)
}

```

----normalization----

```{r}
brain_mat <- as.matrix(brain_data)
brain_mat <- as.matrix(brain_mat)
condition <- as.factor(tis_br)
dds <- DESeqDataSetFromMatrix(brain_mat, DataFrame(condition), ~ condition)
dds <- estimateSizeFactors(dds)
sf <- sizeFactors(dds)
brain_scale <- t(t(brain_mat)/sf)
brain_mat <- brain_scale
```

```{r}
library(EDISON)
k1 <- read.csv("C://ISBD/bicluster code/0228/kclass1.csv")
k2 <- read.csv("C://ISBD/bicluster code/0228/kclass2.csv")
k1 <- matrix(k1[5001:10000,2],1,5000)
k2 <- matrix(k2[15001:20000,2],1,5000)
km <- list()
km[[1]] <- k1
km[[2]] <- k2
psrf(km)
```

```{r}
kc <- which(!is.na(match(id,brain$SAMPID)))
write.csv(kc,"C://ISBD/bicluster code/0228/kc.csv")
kr <- match(brain_gene,name_gene)
write.csv(kr,"C://ISBD/bicluster code/0228/kr.csv")
```

```{r}
heatmap(y[7,,])
```

```{r}
for(i in 1:23){
  heatmap(y[,,i])
}

```

```{r}
for(i in 1:8){
  heatmap(y[i,,])
}

```

```{r}
for(i in 1:13){
  heatmap(y[,i,])
}

```



```{r}
y_alz <- brain_array[,,alzd]
for(i in 1:11){
  heatmap(y_alz[,,i])
}
```

```{r}
parkinson <- read.table("C://ISBD/bicluster code/0317/parkinson.txt",sep="\t",quote = "")
parkinson <- parkinson$V1
pard <- match(parkinson,name_gene)
pard <- na.omit(pard)
pard <- which(!is.na(match(kr,pard)))
```

```{r}
y_par <- brain_array[,,pard]
for(i in 1:13){
  heatmap(y_par[,,i],main = paste("gene", brain_gene[i]))
}
```

```{r}
for (i in 1:383) {
  heatmap(brain_array[,,i],na.rm = TRUE)
}
```

```{r}
library(mice)
library(VIM)
aggr(t(y[,,2]),prop=F,numbers=T)
```

```{r}
signal <- read.table("C://ISBD/bicluster code/0317/signaling.txt",sep="\t",quote = "")
signal <- signal$V1
sd <- match(signal,name_gene)
dels <- which(is.na(sd))
signal <- signal[-dels]
sd <- na.omit(sd)
sd <- which(!is.na(match(kr,sd)))
```

```{r}
y_sig <- brain_array[,,sd]
for(i in 1:9){
  heatmap(y_sig[,,i],main = paste("gene", signal[i]))
}
```

```{r}
gpro <- read.table("g-protein coupled receptor.txt",sep="\t",quote = "")
gpro <- gpro$V1
gd <- match(gpro,name_gene)
dels <- which(is.na(gd))
gpro <- gpro[-dels]
gd <- na.omit(gd)
gd <- which(!is.na(match(kr,gd)))
```

```{r}
y_gpro <- brain_array[,,gd]
for(i in 1:length(gd)){
  heatmap(y_gpro[,,i],main = paste("gene", gpro[i]))
}
```

```{r}
genefo <- read.table("depression.txt",sep="\t",quote = "")
genefo <- genefo$V1
gened <- match(genefo,name_gene)
dels <- which(is.na(gened))
genefo <- genefo[-dels]
gened <- na.omit(gened)
gened <- which(!is.na(match(kr,gened)))
```

```{r}
y_gf <- brain_array[,,gened]
for(i in 1:15){
  heatmap(y[,,i],main = paste("gene", dep_gene[i]))
}
```

```{r}
for(i in 1:15){
  heatmap(y_dep[,,i])
}

```